#!/usr/bin/env python3
"""Regenerates lib/l10n/app_strings.dart from lib/l10n/strings_en.dart.

The English catalogue is the source of truth: every key in it becomes a static
member of `S`. Keys whose value contains {placeholders} become methods with
required named arguments; everything else becomes a plain getter.

Usage:  python3 tool/gen_strings.py
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
L10N = ROOT / 'lib' / 'l10n'

HEADER = '''// GENERATED by tool/gen_strings.py — DO NOT EDIT BY HAND.
//
// Regenerate after changing `strings_en.dart`:
//     python3 tool/gen_strings.py
//
// `S` is a context-free accessor for the active language. It is context-free on
// purpose: hundreds of helper methods in this app build widgets without a
// `BuildContext`, and threading one through all of them would be a far riskier
// change than a single global that `LocaleProvider` swaps.
//
// The whole widget tree is rebuilt when the locale changes (MaterialApp is
// keyed on the locale in `main.dart`), so every `S.*` read is re-evaluated.

import 'strings_bn.dart';
import 'strings_en.dart';
import 'strings_hi.dart';

/// Locale codes this app ships translations for.
const List<String> kSupportedLanguageCodes = ['en', 'bn', 'hi'];

/// Static string table for the currently selected app language.
class S {
  S._();

  static String _code = 'en';
  static Map<String, String> _active = kStringsEn;

  /// Language code currently driving every `S.*` getter.
  static String get code => _code;

  /// Swaps the active catalogue. Unknown codes fall back to English.
  static void load(String code) {
    _code = kSupportedLanguageCodes.contains(code) ? code : 'en';
    switch (_code) {
      case 'bn':
        _active = kStringsBn;
        break;
      case 'hi':
        _active = kStringsHi;
        break;
      default:
        _active = kStringsEn;
    }
  }

  /// Raw lookup with an English fallback, then the key itself as a last resort
  /// so a missing translation shows something readable instead of blank space.
  static String raw(String key) => _active[key] ?? kStringsEn[key] ?? key;

  /// Replaces `{name}` placeholders in [template].
  static String fill(String template, Map<String, Object?> values) {
    var result = template;
    values.forEach((k, v) => result = result.replaceAll('{$k}', '$v'));
    return result;
  }

  /// Abbreviated month names, index 0 = January.
  static List<String> get monthsShort =>
      List<String>.generate(12, (i) => raw('month${i + 1}'));

  /// Abbreviated name for a 1-based [month] number, as `DateTime.month` gives.
  static String monthName(int month) => raw('month$month');
'''


def parse(path, var):
    """Returns (ordered_items, {key: [placeholders]})."""
    src = path.read_text(encoding='utf-8')
    body = src.split(var + ' = {', 1)[1]
    items, holders = [], {}
    for line in body.split('\n'):
        m = re.match(r"\s*//\s*-+\s*(.+?)\s*-+\s*$", line)
        if m:
            items.append(('comment', m.group(1)))
            continue
        m = re.match(r"\s*'([A-Za-z0-9_]+)':", line)
        if m:
            items.append(('key', m.group(1)))
    for key in [v for t, v in items if t == 'key']:
        m = re.search(r"'%s':\s*((?:'(?:[^'\\]|\\.)*'\s*)+)," % re.escape(key), body, re.S)
        holders[key] = sorted(set(re.findall(r'\{(\w+)\}', m.group(1) if m else '')))
    return items, holders


def main():
    items, holders = parse(L10N / 'strings_en.dart', 'kStringsEn')
    en_keys = [v for t, v in items if t == 'key']

    # Key-parity check against every translation.
    problems = []
    for code, var in (('bn', 'kStringsBn'), ('hi', 'kStringsHi')):
        tr_items, tr_holders = parse(L10N / f'strings_{code}.dart', var)
        tr_keys = {v for t, v in tr_items if t == 'key'}
        for k in en_keys:
            if k not in tr_keys:
                problems.append(f'{code}: missing key "{k}" (will fall back to English)')
        for k in tr_keys - set(en_keys):
            problems.append(f'{code}: stray key "{k}" not present in English')
        for k in tr_keys & set(en_keys):
            if tr_holders[k] != holders[k]:
                problems.append(
                    f'{code}: placeholder mismatch on "{k}" — '
                    f'en{holders[k]} vs {code}{tr_holders[k]}')

    lines = [HEADER]
    for typ, val in items:
        if typ == 'comment':
            lines.append('\n  // ---- %s' % val)
            continue
        ph = holders[val]
        if ph:
            args = ', '.join('required Object %s' % p for p in ph)
            mapped = ', '.join("'%s': %s" % (p, p) for p in ph)
            lines.append("  static String %s({%s}) =>\n      fill(raw('%s'), {%s});"
                         % (val, args, val, mapped))
        else:
            lines.append("  static String get %s => raw('%s');" % (val, val))
    lines.append('}')
    (L10N / 'app_strings.dart').write_text('\n'.join(lines) + '\n', encoding='utf-8')

    print(f'Generated lib/l10n/app_strings.dart with {len(en_keys)} keys.')
    if problems:
        print('\nTranslation problems:')
        for p in problems:
            print('  -', p)
        return 1
    print('All translations are key-complete. ✅')
    return 0


if __name__ == '__main__':
    sys.exit(main())
