// GENERATED by tool/gen_strings.py — DO NOT EDIT BY HAND.
//
// Regenerate after changing `strings_en.dart`:
//     python3 tool/gen_strings.py
//
// `S` is a context-free accessor for the active language. It is context-free on
// purpose: hundreds of helper methods in this app build widgets without a
// `BuildContext`, and threading one through all of them would be a far riskier
// change than a single global that `LocaleProvider` swaps.
//
// The whole widget tree is rebuilt when the locale changes (MaterialApp is
// keyed on the locale in `main.dart`), so every `S.*` read is re-evaluated.

import 'strings_bn.dart';
import 'strings_en.dart';
import 'strings_hi.dart';

/// Locale codes this app ships translations for.
const List<String> kSupportedLanguageCodes = ['en', 'bn', 'hi'];

/// Static string table for the currently selected app language.
class S {
  S._();

  static String _code = 'en';
  static Map<String, String> _active = kStringsEn;

  /// Language code currently driving every `S.*` getter.
  static String get code => _code;

  /// Swaps the active catalogue. Unknown codes fall back to English.
  static void load(String code) {
    _code = kSupportedLanguageCodes.contains(code) ? code : 'en';
    switch (_code) {
      case 'bn':
        _active = kStringsBn;
        break;
      case 'hi':
        _active = kStringsHi;
        break;
      default:
        _active = kStringsEn;
    }
  }

  /// Raw lookup with an English fallback, then the key itself as a last resort
  /// so a missing translation shows something readable instead of blank space.
  static String raw(String key) => _active[key] ?? kStringsEn[key] ?? key;

  /// Replaces `{name}` placeholders in [template].
  static String fill(String template, Map<String, Object?> values) {
    var result = template;
    values.forEach((k, v) => result = result.replaceAll('{$k}', '$v'));
    return result;
  }

  /// Abbreviated month names, index 0 = January.
  static List<String> get monthsShort =>
      List<String>.generate(12, (i) => raw('month${i + 1}'));

  /// Abbreviated name for a 1-based [month] number, as `DateTime.month` gives.
  static String monthName(int month) => raw('month$month');


  // ---- common
  static String get appTitle => raw('appTitle');
  static String get cancel => raw('cancel');
  static String get save => raw('save');
  static String get close => raw('close');
  static String get ok => raw('ok');
  static String get retry => raw('retry');
  static String get loading => raw('loading');
  static String get pleaseWait => raw('pleaseWait');
  static String get all => raw('all');
  static String get items => raw('items');
  static String get today => raw('today');
  static String get yesterday => raw('yesterday');
  static String daysAgo({required Object n}) =>
      fill(raw('daysAgo'), {'n': n});
  static String get points => raw('points');
  static String get seconds => raw('seconds');
  static String get coins => raw('coins');
  static String get gems => raw('gems');
  static String get score => raw('score');
  static String get correct => raw('correct');
  static String get wrong => raw('wrong');
  static String get skipped => raw('skipped');
  static String get time => raw('time');
  static String get accuracy => raw('accuracy');
  static String get you => raw('you');
  static String get newLabel => raw('newLabel');
  static String get owned => raw('owned');
  static String get locked => raw('locked');
  static String get active => raw('active');
  static String get unlock => raw('unlock');
  static String get goToShop => raw('goToShop');
  static String get quantity => raw('quantity');
  static String get cost => raw('cost');
  static String get currency => raw('currency');
  static String get item => raw('item');

  // ---- navigation
  static String get navHome => raw('navHome');
  static String get navExplore => raw('navExplore');
  static String get navRanking => raw('navRanking');
  static String get navProfile => raw('navProfile');

  // ---- greetings
  static String get greetStillAwake => raw('greetStillAwake');
  static String get greetMorning => raw('greetMorning');
  static String get greetAfternoon => raw('greetAfternoon');
  static String get greetEvening => raw('greetEvening');
  static String get greetNight => raw('greetNight');

  // ---- dashboard
  static String get dashPlayYourWay => raw('dashPlayYourWay');
  static String get dashQuickActions => raw('dashQuickActions');
  static String get dashSeeAll => raw('dashSeeAll');
  static String get dashLiveToday => raw('dashLiveToday');
  static String get dashLeaderboard => raw('dashLeaderboard');
  static String get dashViewFull => raw('dashViewFull');
  static String get dashDailyChampion => raw('dashDailyChampion');
  static String get dashDailyChampionTitle => raw('dashDailyChampionTitle');
  static String get dashExploreMore => raw('dashExploreMore');
  static String get dashMoreOptions => raw('dashMoreOptions');
  static String get dashDayStreak => raw('dashDayStreak');
  static String get dashAccuracyShort => raw('dashAccuracyShort');
  static String get dashAdminPanel => raw('dashAdminPanel');
  static String get dashDailyQuiz => raw('dashDailyQuiz');
  static String get dashChapters => raw('dashChapters');
  static String get dashHistory => raw('dashHistory');
  static String get dashBattle => raw('dashBattle');
  static String get dashRewards => raw('dashRewards');
  static String get dashShop => raw('dashShop');

  // ---- daily quiz
  static String get quizQuitTitle => raw('quizQuitTitle');
  static String get quizQuitBody => raw('quizQuitBody');
  static String get quizQuit => raw('quizQuit');
  static String get quizNoFiftyFifty => raw('quizNoFiftyFifty');
  static String get quizFiftyFiftyUsed => raw('quizFiftyFiftyUsed');
  static String get quizFiftyFiftyBlocked => raw('quizFiftyFiftyBlocked');
  static String get quizNoFreeze => raw('quizNoFreeze');
  static String get quizFreezeUsed => raw('quizFreezeUsed');
  static String get quizFreezeBlocked => raw('quizFreezeBlocked');
  static String get quizNoSkip => raw('quizNoSkip');
  static String get quizSkipUsed => raw('quizSkipUsed');
  static String get quizSkipBlocked => raw('quizSkipBlocked');
  static String get quizNoHint => raw('quizNoHint');
  static String get quizHintUsed => raw('quizHintUsed');
  static String get quizHintBlocked => raw('quizHintBlocked');
  static String get quizNoPoll => raw('quizNoPoll');
  static String get quizPollUsed => raw('quizPollUsed');
  static String get quizPollBlocked => raw('quizPollBlocked');

  // ---- chapter
  static String get chapterAllSubjects => raw('chapterAllSubjects');
  static String get chapterBankTitle => raw('chapterBankTitle');
  static String chapterCount({required Object n}) =>
      fill(raw('chapterCount'), {'n': n});
  static String chapterQuestionCount({required Object n}) =>
      fill(raw('chapterQuestionCount'), {'n': n});
  static String chapterShort({required Object n}) =>
      fill(raw('chapterShort'), {'n': n});
  static String get chapterLockedMsg => raw('chapterLockedMsg');

  // ---- leaderboard
  static String get lbTitle => raw('lbTitle');
  static String get lbYourPosition => raw('lbYourPosition');
  static String get lbNoScoresToday => raw('lbNoScoresToday');
  static String get lbNoScoresBody => raw('lbNoScoresBody');
  static String get lbNoChampions => raw('lbNoChampions');
  static String get lbFetching => raw('lbFetching');
  static String lbReward({required Object gift}) =>
      fill(raw('lbReward'), {'gift': gift});
  static String lbChampScore({required Object score, required Object time}) =>
      fill(raw('lbChampScore'), {'score': score, 'time': time});

  // ---- profile
  static String get profileTitle => raw('profileTitle');
  static String get profileChangeAvatar => raw('profileChangeAvatar');
  static String get profileEdit => raw('profileEdit');
  static String get profileSave => raw('profileSave');
  static String get profileDetails => raw('profileDetails');
  static String get profilePerformance => raw('profilePerformance');
  static String get profileBadges => raw('profileBadges');
  static String get profileNoBadges => raw('profileNoBadges');
  static String get profileUsername => raw('profileUsername');
  static String get profileFullName => raw('profileFullName');
  static String get profileGender => raw('profileGender');
  static String get profileEmail => raw('profileEmail');
  static String get profileChange => raw('profileChange');
  static String get profileMale => raw('profileMale');
  static String get profileFemale => raw('profileFemale');
  static String get profileSelectGender => raw('profileSelectGender');
  static String get profileDayStreak => raw('profileDayStreak');
  static String get profileQuizzesPlayed => raw('profileQuizzesPlayed');
  static String get profileCorrectAnswers => raw('profileCorrectAnswers');
  static String get profileBestDailyScore => raw('profileBestDailyScore');
  static String get profileBattlesWon => raw('profileBattlesWon');
  static String get profileAvgTime => raw('profileAvgTime');
  static String get profileLongestStreak => raw('profileLongestStreak');
  static String get profileNameEffect => raw('profileNameEffect');
  static String get profileNameEffectHint => raw('profileNameEffectHint');
  static String get profileMyPurchases => raw('profileMyPurchases');
  static String get profileMyPurchasesHint => raw('profileMyPurchasesHint');
  static String get profileSettings => raw('profileSettings');
  static String get profileDarkMode => raw('profileDarkMode');
  static String get profileSound => raw('profileSound');
  static String get profileVibration => raw('profileVibration');
  static String get profileNotifications => raw('profileNotifications');
  static String get profileAbout => raw('profileAbout');
  static String get profileRateApp => raw('profileRateApp');
  static String get profileShare => raw('profileShare');
  static String get profilePrivacy => raw('profilePrivacy');
  static String get profileTerms => raw('profileTerms');
  static String profileVersion({required Object v}) =>
      fill(raw('profileVersion'), {'v': v});
  static String get profileSignIn => raw('profileSignIn');
  static String get profileSignOut => raw('profileSignOut');
  static String get profileSignOutConfirm => raw('profileSignOutConfirm');
  static String get profileSignInPrompt => raw('profileSignInPrompt');
  static String get profileGuestMode => raw('profileGuestMode');
  static String get profileRegistered => raw('profileRegistered');
  static String get profileGoogleAccount => raw('profileGoogleAccount');
  static String get profileConnected => raw('profileConnected');
  static String get profileNotConnected => raw('profileNotConnected');
  static String get profileUpdated => raw('profileUpdated');
  static String get profileAvatarUpdated => raw('profileAvatarUpdated');
  static String get profileSignedInGoogle => raw('profileSignedInGoogle');
  static String get profileEffectNotOwned => raw('profileEffectNotOwned');
  static String get profilePlayerFallback => raw('profilePlayerFallback');

  // ---- avatar
  static String get avatarChoose => raw('avatarChoose');
  static String get avatarCurrent => raw('avatarCurrent');
  static String get avatarTapToChange => raw('avatarTapToChange');
  static String get avatarCloudSection => raw('avatarCloudSection');
  static String get avatarPremium => raw('avatarPremium');
  static String get avatarAlreadyOwned => raw('avatarAlreadyOwned');
  static String get avatarNotEnoughGems => raw('avatarNotEnoughGems');
  static String get avatarPremiumHint => raw('avatarPremiumHint');
  static String avatarUnlockTitle({required Object name}) =>
      fill(raw('avatarUnlockTitle'), {'name': name});
  static String avatarUnlockBody({required Object cost}) =>
      fill(raw('avatarUnlockBody'), {'cost': cost});
  static String avatarUnlocked({required Object name}) =>
      fill(raw('avatarUnlocked'), {'name': name});

  // ---- shop
  static String get shopTitle => raw('shopTitle');
  static String get shopAllItems => raw('shopAllItems');
  static String get shopCloudItems => raw('shopCloudItems');
  static String get shopEmptyCategory => raw('shopEmptyCategory');
  static String shopItemCount({required Object n}) =>
      fill(raw('shopItemCount'), {'n': n});
  static String get shopOwnedCheck => raw('shopOwnedCheck');
  static String get shopNotOwned => raw('shopNotOwned');
  static String shopOwnedTimes({required Object n}) =>
      fill(raw('shopOwnedTimes'), {'n': n});
  static String get shopBestValue => raw('shopBestValue');
  static String get shopUnlockedForever => raw('shopUnlockedForever');
  static String get shopAlreadyOwn => raw('shopAlreadyOwn');
  static String shopNotEnough({required Object currency}) =>
      fill(raw('shopNotEnough'), {'currency': currency});
  static String shopAdded({required Object n}) =>
      fill(raw('shopAdded'), {'n': n});
  static String get shopCatAll => raw('shopCatAll');
  static String get shopCatPowerUps => raw('shopCatPowerUps');
  static String get shopCatBoosters => raw('shopCatBoosters');
  static String get shopCatShields => raw('shopCatShields');
  static String get shopCatAvatars => raw('shopCatAvatars');
  static String get shopCatEffects => raw('shopCatEffects');
  static String get shopCatBadges => raw('shopCatBadges');
  static String get shopCatPacks => raw('shopCatPacks');
  static String shopCoinsLabel({required Object n}) =>
      fill(raw('shopCoinsLabel'), {'n': n});
  static String shopGemsLabel({required Object n}) =>
      fill(raw('shopGemsLabel'), {'n': n});

  // ---- purchase history
  static String get purchaseTitle => raw('purchaseTitle');
  static String get purchaseNone => raw('purchaseNone');
  static String purchaseNoneFiltered({required Object filter}) =>
      fill(raw('purchaseNoneFiltered'), {'filter': filter});
  static String get purchaseEmptyBody => raw('purchaseEmptyBody');
  static String get purchaseOrders => raw('purchaseOrders');
  static String get purchaseTotalSpent => raw('purchaseTotalSpent');
  static String get purchaseCoinsSpent => raw('purchaseCoinsSpent');
  static String get purchaseGemsSpent => raw('purchaseGemsSpent');
  static String purchasedOn({required Object date}) =>
      fill(raw('purchasedOn'), {'date': date});

  // ---- rewards
  static String get rewardsTitle => raw('rewardsTitle');
  static String get rewardsYourGifts => raw('rewardsYourGifts');
  static String get rewardsTapPrize => raw('rewardsTapPrize');
  static String get rewardsNone => raw('rewardsNone');
  static String get rewardsWinDaily => raw('rewardsWinDaily');
  static String get rewardsWinDailyBody => raw('rewardsWinDailyBody');
  static String get rewardsClaimNow => raw('rewardsClaimNow');
  static String get rewardsClaimed => raw('rewardsClaimed');
  static String get rewardsProcessing => raw('rewardsProcessing');
  static String get rewardsProcessingCaps => raw('rewardsProcessingCaps');
  static String get rewardsShipped => raw('rewardsShipped');
  static String get rewardsShippedCaps => raw('rewardsShippedCaps');
  static String get rewardsDelivered => raw('rewardsDelivered');
  static String get rewardsDeliveredCaps => raw('rewardsDeliveredCaps');
  static String get rewardsDeliveringTo => raw('rewardsDeliveringTo');
  static String get rewardsDeliveryStatus => raw('rewardsDeliveryStatus');
  static String get rewardsDeliveryAddress => raw('rewardsDeliveryAddress');
  static String get rewardsDigital => raw('rewardsDigital');
  static String get rewardsRedeemCode => raw('rewardsRedeemCode');
  static String get rewardsCopyCode => raw('rewardsCopyCode');
  static String get rewardsCodeCopied => raw('rewardsCodeCopied');
  static String get rewardsRedeemHint => raw('rewardsRedeemHint');
  static String get rewardsRedeemMark => raw('rewardsRedeemMark');
  static String get rewardsRedeemed => raw('rewardsRedeemed');
  static String get rewardsSubmitClaim => raw('rewardsSubmitClaim');
  static String get rewardsPhone => raw('rewardsPhone');
  static String get rewardsAddress => raw('rewardsAddress');
  static String get rewardsPin => raw('rewardsPin');
  static String get rewardsErrName => raw('rewardsErrName');
  static String get rewardsErrPhone => raw('rewardsErrPhone');
  static String get rewardsErrAddress => raw('rewardsErrAddress');
  static String get rewardsErrPin => raw('rewardsErrPin');

  // ---- quiz  history
  static String get historyTitle => raw('historyTitle');
  static String get historyNone => raw('historyNone');
  static String get historyEmptyBody => raw('historyEmptyBody');
  static String get historyTotalScore => raw('historyTotalScore');
  static String get historyQuizzes => raw('historyQuizzes');
  static String get historyAvgAccuracy => raw('historyAvgAccuracy');
  static String get historyDaily => raw('historyDaily');
  static String get historyChapter => raw('historyChapter');
  static String get historyDailyCaps => raw('historyDailyCaps');
  static String get historyChapterCaps => raw('historyChapterCaps');
  static String historyPlayedOn({required Object date}) =>
      fill(raw('historyPlayedOn'), {'date': date});

  // ---- quiz result
  static String get resultCompleted => raw('resultCompleted');
  static String get resultSummary => raw('resultSummary');
  static String get resultTotalScore => raw('resultTotalScore');
  static String get resultReview => raw('resultReview');
  static String get resultLeaderboard => raw('resultLeaderboard');
  static String get resultBackHome => raw('resultBackHome');
  static String get resultPerfect => raw('resultPerfect');
  static String get resultSaveScore => raw('resultSaveScore');
  static String get resultGuestBody => raw('resultGuestBody');
  static String get resultGoogleSignIn => raw('resultGoogleSignIn');
  static String get resultSigningIn => raw('resultSigningIn');
  static String get resultSignedIn => raw('resultSignedIn');
  static String get reviewTitle => raw('reviewTitle');
  static String get reviewNone => raw('reviewNone');
  static String get reviewYourAnswer => raw('reviewYourAnswer');
  static String get reviewCorrectAnswer => raw('reviewCorrectAnswer');
  static String get reviewExplanation => raw('reviewExplanation');
  static String reviewQuestionNo({required Object n}) =>
      fill(raw('reviewQuestionNo'), {'n': n});

  // ---- battle
  static String get battlePlayer => raw('battlePlayer');
  static String battleBotCorrect({required Object n}) =>
      fill(raw('battleBotCorrect'), {'n': n});
  static String get battleArena => raw('battleArena');
  static String battleRulesLine({required Object n}) =>
      fill(raw('battleRulesLine'), {'n': n});
  static String get battleChooseDifficulty => raw('battleChooseDifficulty');
  static String get battleEasy => raw('battleEasy');
  static String get battleEasyDesc => raw('battleEasyDesc');
  static String get battleNormal => raw('battleNormal');
  static String get battleNormalDesc => raw('battleNormalDesc');
  static String get battleHard => raw('battleHard');
  static String get battleHardDesc => raw('battleHardDesc');
  static String get battleStartFinding => raw('battleStartFinding');
  static String get battleSearching => raw('battleSearching');
  static String get battleSearchingHint => raw('battleSearchingHint');
  static String get battleCancelSearch => raw('battleCancelSearch');
  static String get battleBotMatch => raw('battleBotMatch');
  static String get battleLiveMatch => raw('battleLiveMatch');
  static String get battleFoundHint => raw('battleFoundHint');
  static String get battleGetReady => raw('battleGetReady');
  static String get battleRematch => raw('battleRematch');
  static String get battleBackHome => raw('battleBackHome');
  static String get battleWinTitle => raw('battleWinTitle');
  static String get battleDrawTitle => raw('battleDrawTitle');
  static String get battleLoseTitle => raw('battleLoseTitle');

  // ---- language
  static String get languageTitle => raw('languageTitle');
  static String get languageSubtitle => raw('languageSubtitle');
  static String get languageAppSection => raw('languageAppSection');
  static String get languageSystemDefault => raw('languageSystemDefault');
  static String get languageChanged => raw('languageChanged');
  static String get languageEnglish => raw('languageEnglish');
  static String get languageBengali => raw('languageBengali');
  static String get languageHindi => raw('languageHindi');

  // ---- dates
  static String get month1 => raw('month1');
  static String get month2 => raw('month2');
  static String get month3 => raw('month3');
  static String get month4 => raw('month4');
  static String get month5 => raw('month5');
  static String get month6 => raw('month6');
  static String get month7 => raw('month7');
  static String get month8 => raw('month8');
  static String get month9 => raw('month9');
  static String get month10 => raw('month10');
  static String get month11 => raw('month11');
  static String get month12 => raw('month12');

  // ---- chapter  sets
  static String get setsTitle => raw('setsTitle');
  static String get setsHistoryTab => raw('setsHistoryTab');
  static String setsSet({required Object n}) =>
      fill(raw('setsSet'), {'n': n});
  static String setsSetOf({required Object n, required Object total}) =>
      fill(raw('setsSetOf'), {'n': n, 'total': total});
  static String setsQuestions({required Object n}) =>
      fill(raw('setsQuestions'), {'n': n});
  static String setsContinue({required Object n}) =>
      fill(raw('setsContinue'), {'n': n});
  static String setsStart({required Object n}) =>
      fill(raw('setsStart'), {'n': n});
  static String get setsAllDone => raw('setsAllDone');
  static String get setsAllDoneBody => raw('setsAllDoneBody');
  static String setsLocked({required Object n}) =>
      fill(raw('setsLocked'), {'n': n});
  static String get setsCleared => raw('setsCleared');
  static String setsBest({required Object correct, required Object total}) =>
      fill(raw('setsBest'), {'correct': correct, 'total': total});
  static String get setsRetry => raw('setsRetry');
  static String get setsPractice => raw('setsPractice');
  static String get setsPracticeNote => raw('setsPracticeNote');
  static String get setsPracticeBanner => raw('setsPracticeBanner');
  static String get setsNoHistory => raw('setsNoHistory');
  static String get setsNoHistoryBody => raw('setsNoHistoryBody');
  static String setsAttempts({required Object n}) =>
      fill(raw('setsAttempts'), {'n': n});
  static String get setsEmpty => raw('setsEmpty');
  static String get setsEmptyBody => raw('setsEmptyBody');
  static String setsPlayedOn({required Object date}) =>
      fill(raw('setsPlayedOn'), {'date': date});
}
